name: build

on:
  pull_request:
    branches:
      - main

jobs:
  sphinx:
    runs-on: ubuntu-latest
    env:
      SPHINXOPTS: -D gettext_auto_build=True -n
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install apt packages
        run: sudo apt-get install --no-install-recommends -y gettext
      - name: Restore pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('.github/workflows/deploy.yml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install pip packages
        run: >
          pip install
          sphinx==4.5.0
          myst-parser==0.17.2
          sphinx-rtd-theme==1.0.0
      - name: Make html/fr
        run: make html/fr O='-w errors.html.fr.log'
      - name: Make html/en
        run: make html/en O='-w errors.html.en.log'
      - name: Collect Sphinx errors
        run: |
          echo '::add-matcher::.github/matchers/sphinx.json'
          sed 's/\x1b\[[0-9;]*[mGKHF]//g' errors.*.log | sort -u
          echo '::remove-matcher owner=sphinx::'
